"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import active_record.connection

class DummyConnector(active_record.connection.IConnector):
	@property
	def operations(self):
		return active_record.connection.Operations

	def table_exists(self, table_name):
		return True

	def get_table_columns(self, table_name):
		return {"id" : int, "integer" : int}

	def get_table_primary_key(self, table_name):
		return "id"

	def table_record_exists(self, table_name, criteria):
		return True

	def execute_operation(self, operation, column, from_table = None, where = None, group = None, having = None, **kargs):
		return 1

	def execute_query(self, select = None, from_table = None, where = None, distinct = False, group = None, limit = None, having = None, includes = [], joins = [], offset = None, order = None, uniq = False):
		return []
