"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from dummy_connector import DummyConnector
import active_record.connection
active_record.connection.ConnectionManager.instance.connector = DummyConnector()
import active_record.base

class DummyActiveRecord(active_record.base.ActiveRecord):
	pass
