"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from .. import util

class ActiveRecordMetaClass(type):
	def __init__(cls, name, bases, dct):
		type.__init__(cls, name, bases, dct)

		tokens = util.CaseConverter.convert_to_snake_case(name).rsplit("_", 1)
		last_token = tokens[-1]
		left_tokens = tokens[-2] + "_" if len(tokens) > 1 else ""
		table_name = left_tokens + util.Pluralizer.pluralize(last_token)

		util.ActiveRecordInitializer.initialize(cls, table_name)

class ActiveRecord(object):
	__metaclass__ = ActiveRecordMetaClass
