"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import abc

class IFinder(object):
	__metaclass__ = abc.ABCMeta

	@abc.abstractmethod
	def exists(self, criteria = None):
		""""""

	@abc.abstractmethod
	def find(self, arguments):
		""""""

	@abc.abstractmethod
	def find_by(self, criteria):
		""""""

	@abc.abstractmethod
	def first(self, limit = None):
		""""""

	@abc.abstractmethod
	def last(self, limit = None):
		""""""

	@abc.abstractmethod
	def take(self, limit = None):
		""""""
