"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import abc

class IQuery(object):
	__metaclass__ = abc.ABCMeta

	@abc.abstractmethod
	def distinct(self, value = True):
		""""""

	@abc.abstractmethod
	def eager_load(self, arguments):
		""""""

	#@abc.abstractmethod
	#def from(self, value, subquery_name = None):
	#	""""""

	@abc.abstractmethod
	def group(self, arguments):
		""""""

	@abc.abstractmethod
	def having(self, clause):
		""""""

	def includes(self, arguments):
		""""""

	@abc.abstractmethod
	def joins(self, arguments):
		""""""

	@abc.abstractmethod
	def limit(self, value):
		""""""

	@abc.abstractmethod
	def none(self):
		""""""

	@abc.abstractmethod
	def offset(self, value):
		""""""

	@abc.abstractmethod
	def order(self, arguments):
		""""""

	@abc.abstractmethod
	def readonly(self, value = True):
		""""""

	@abc.abstractmethod
	def references(self, arguments):
		""""""

	@abc.abstractmethod
	def where(self, clause):
		""""""
