"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import active_record
from test import mock

class PropertyAttacherTestCase(unittest.TestCase):
	def test_type_safe_attach_property(self):
		active_record.util.PropertyAttacher.attach_property(mock.DummyClass, "property", int)
		dummy_object = mock.DummyClass()

		self.assertEqual(dummy_object.property, None)

		self.assertRaises(TypeError, dummy_object.property, "some string")

		dummy_object.property = 5

		self.assertEqual(dummy_object.property, 5)

		del dummy_object.property

		self.assertEqual(dummy_object.property, None)

	def test_non_type_safe_attach_property(self):
		active_record.util.PropertyAttacher.attach_property(mock.DummyClass, "property")
		dummy_object = mock.DummyClass()

		self.assertEqual(dummy_object.property, None)

		dummy_object.property = 5

		self.assertEqual(dummy_object.property, 5)

		dummy_object.property = "some string"

		self.assertEqual(dummy_object.property, "some string")
