"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
from test import mock
import active_record.connection

class ConnectionManagerTestCase(unittest.TestCase):
	def test_instance(self):
		self.assertEqual(active_record.connection.ConnectionManager.instance.__class__, active_record.connection.ConnectionManager)

	def test_connector(self):
		success = False

		try:
			active_record.connection.ConnectionManager.instance.connector = ""
		except TypeError:
			success = True

		self.assertTrue(success)

		connector = mock.DummyConnector()
		active_record.connection.ConnectionManager.instance.connector = connector

		self.assertEqual(active_record.connection.ConnectionManager.instance.connector, connector)
