"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import active_record.connection

class IConnectorTestCase(unittest.TestCase):
	def test_get_table_columns(self):
		connector = active_record.connection.IConnector()
		success = False

		try:
			connector.get_table_columns("")
		except NotImplementedError:
			success = True

		self.assertTrue(success)
