"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class class_property(property):
	def __get__(self, cls, type = None):
		return self.fget.__get__(None, type)()
