"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class IConnector(object):
	def get_table_columns(self, table_name):
		raise NotImplementedError()
