"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from .. import decorator
from .. import interface

@decorator.singleton
class ConnectionManager(object):
	def __init__(self):
		self._connector = None

	@property
	def connector(self):
		return self._connector

	@connector.setter
	def connector(self, connector):
		if not isinstance(connector, interface.IConnector):
			raise TypeError("connector must be a subclass of IConnector")

		self._connector = connector
