"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from .. import decorator
from connector import IConnector

@decorator.singleton
class ConnectionManager(object):
	def __init__(self):
		self._connector = None

	@property
	def connector(self):
		return self._connector

	@connector.setter
	def connector(self, connector):
		if not isinstance(connector, IConnector):
			raise ValueError("connector must extends IConnector")

		self._connector = connector
