"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import abc

class IConnector(object):
	__metaclass__ = abc.ABCMeta

	@abc.abstractproperty
	def operations(self):
		"""Gets the connector operations."""

	@abc.abstractmethod
	def table_exists(self, table_name):
		"""Verifies if table exists in the database."""

	@abc.abstractmethod
	def get_table_columns(self, table_name):
		"""Gets the table columns from the database."""

	@abc.abstractmethod
	def get_table_primary_key(self, table_name):
		"""Gets the table primary key from the database."""

	@abc.abstractmethod
	def execute_operation(self, operation, column, from_table = None, where = None, group = None, having = None, **kargs):
		"""Executes the value for the operation over the given table column."""

	@abc.abstractmethod
	def execute_query(self, select = None, from_table = None, where = None, distinct = False, group = None, limit = None, having = None, includes = [], joins = [], offset = None, order = None, uniq = False):
		"""Executes the query in the database."""
