"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""
from class_property import class_property

def singleton(cls):
	def get_instance(cls):
		instance = getattr(cls, "_instance", None)

		if instance is None:
			instance = cls()
			setattr(cls, "_instance", instance)

		return instance

	setattr(cls, "instance", class_property(classmethod(get_instance)))

	return cls
