"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import active_record
from test import mock

class ActiveRecordInitializerTestCase(unittest.TestCase):
	def test_initialize(self):
		active_record.util.ActiveRecordInitializer.initialize(mock.DummyClass, "dummy_classes")

		self.assertEqual(mock.DummyClass.table_name, "dummy_classes")
