"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
from test import mock
import active_record.connection
active_record.connection.ConnectionManager.instance.connector = mock.DummyConnector()
import active_record.base

class ActiveRcordTestCase(unittest.TestCase):
	def test_active_record(self):
		class ActiveRecord(active_record.base.ActiveRecord):
			pass

		record = ActiveRecord()

		self.assertTrue(hasattr(record, "integer"))
