"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from context_container import ContextContainer

class Calculation(ContextContainer):
	def __init__(self):
		ContextContainer.__init__(self)

	def average(cls, column):
		return cls.calculate(connection.ConnectionManager.instance.connector.operations.average, column)

	def calculate(cls, operation, column):
		return connection.ConnectionManager.instance.connector.execute_table_operation(cls.table_name, operation, column)

	def count(cls, column = None):
		return cls.calculate(connection.ConnectionManager.instance.connector.operations.count, column)

	def ids(cls):
		return cls.pluck(cls.primary_key)

	def maximum(cls, column):
		return cls.calculate(connection.ConnectionManager.instance.connector.operations.maximum, column)

	def minimum(cls, column):
		return cls.calculate(connection.ConnectionManager.instance.connector.operations.minimum, column)

	def pluck(cls, *columns):
		return connection.ConnectionManager.instance.connector.get_table_records(columns=columns)

	def sum(cls, column):
		return cls.calculate(connection.ConnectionManager.instance.connector.operations.sum, column)
