"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class Context(dict):
	class Scopes(object):
		class __metaclass__(type):
			@property
			def DISTINCT(cls):
				return "DISTINCT"

			@property
			def FROM(cls):
				return "FROM"

			@property
			def GROUP(cls):
				return "GROUP BY"

			@property
			def HAVING(cls):
				return "HAVING"

			@property
			def INCLUDES(cls):
				return "INCLUDES"

			@property
			def JOINS(cls):
				return "JOINS"

			@property
			def LIMIT(cls):
				return "LIMIT"

			@property
			def OFFSET(cls):
				return "OFFSET"

			@property
			def ORDER(cls):
				return "ORDER BY"

			@property
			def SELECT(cls):
				return "SELECT"

			@property
			def WHERE(cls):
				return "WHERE"

	def __init__(self, *args):
		dict.__init__(self, args)

		self[self.__class__.Scopes.INCLUDES] = []
		self[self.__class__.Scopes.JOINS] = []
		self[self.__class__.Scopes.WHERE] = []
