"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class Operations(object):
	class __metaclass__(type):
		@property
		def average(cls):
			return "AVG"

		@property
		def count(cls):
			return "COUNT"

		@property
		def maximum(cls):
			return "MAX"

		@property
		def minimum(cls):
			return "MIN"

		@property
		def sum(cls):
			return "SUM"
