"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class Orders(object):
	class __metaclass__(type):
		@property
		def ascendant(cls):
			return "ASC"

		def descendant(cls):
			return "DESC"
