"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from finder import Finder

class Relation(Finder):
	def __init__(self):
		Finder.__init__(self)
