"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from query import Query
from .. import connection
from .. import util

class Calculation(Query):
	def __init__(self):
		Query.__init__(self)

	def average(self, column):
		return self.calculate(connection.ConnectionManager.instance.connector.operations.average, column)

	def calculate(self, operation, column):
		return connection.ConnectionManager.instance.connector.execute_operation(operation, column, **self.context)

	def count(self, column = None):
		return self.calculate(connection.ConnectionManager.instance.connector.operations.count, column)

	def ids(self):
		active_record = util.ActiveRecordHolder.instance.get_active_record_by_table_name(self.context["from_table"])

		return self.pluck(active_record.primary_key if active_record is not None else "id")

	def maximum(self, column):
		return self.calculate(connection.ConnectionManager.instance.connector.operations.maximum, column)

	def minimum(self, column):
		return self.calculate(connection.ConnectionManager.instance.connector.operations.minimum, column)

	def pluck(self, *columns):
		self.unescope("select").select(*columns)
		result = []

		for record in connection.ConnectionManager.instance.connector.execute_query(**self.context):
			result.extend(record.values())

		return result

	def sum(self, column):
		return self.calculate(connection.ConnectionManager.instance.connector.operations.sum, column)
