"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from context import Context

class ContextContainer(object):
	def __init__(self):
		self._context = Context()

	@property
	def context(self):
		return self._context
