"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class ContextContainer(object):
	def __init__(self):
		_context = {}

	@property
	def context(self):
		return self._context
