"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

from context_container import ContextContainer

class Query(ContextContainer):
	def __init__(self):
		ContextContainer.__init__(self)
