"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

class QueryMetaclass(type):
	def distinct(cls, value = True):
		pass

	def from_table(cls, value, subquery_name = None):
		pass

	def group(cls, *args):
		pass

	def having(cls, options, *values):
		pass

	def includes(cls, *args):
		pass

	def joins(cls, *args):
		pass

	def limit(cls, value):
		pass

	def none(cls):
		pass

	def offset(cls, value):
		pass

	def order(cls, *args):
		pass

	def preload(cls, *args):
		pass

	def references(cls, *args):
		pass

	def reorder(cls, *args):
		pass

	def reverse_order(cls):
		pass

	def select(cls, *fields):
		pass

	def uniq(cls, value = True):
		pass

	def unescope(cls, *args):
		pass

	def where(cls, options, *values):
		pass
