"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
from test import mock
import active_record.connection
active_record.connection.ConnectionManager.instance.connector = mock.DummyConnector()
import active_record

class BelongsToTestCase(unittest.TestCase):
	def test_non_active_record_belongs_to(self):
		class Owner(active_record.base.ActiveRecord):
			pass

		success = False

		try:
			@active_record.decorator.belongs_to(Owner)
			class Belonger(object):
				pass
		except TypeError:
			success = True

		self.assertTrue(success)

	def test_belongs_to_a_non_active_record(self):
		class Owner(object):
			pass

		success = False

		try:
			@active_record.decorator.belongs_to(Owner)
			class Belonger(active_record.base.ActiveRecord):
				pass
		except TypeError:
			success = True

		self.assertTrue(success)

	def test_belongs_to(self):
		class Owner(active_record.base.ActiveRecord):
			pass

		@active_record.decorator.belongs_to(Owner)
		class Belonger(active_record.base.ActiveRecord):
			owner_id = None

		belonger = Belonger()

		self.assertTrue(hasattr(belonger, "owner"))
