"""
Generated by <Python Project Utils>
Visit the project in http://code.google.com/p/python-project-utils/
"""

import unittest
import active_record

class SingletonTestCase(unittest.TestCase):
	def test_singleton(self):
		@active_record.decorator.singleton
		class DummySingleton:
			pass

		self.assertEqual(DummySingleton.instance.__class__, DummySingleton)
